### ISSUE TITLE
alteon_config_snmpv3_notify module fails __  json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by EmmerichL** [Radware/radware-ansible#92]
##### SEVERITY
Low

##### SUMMARY
Operating System: Red Hat Enterprise Linux release 8.3 (Ootpa)
Ansible Version: 2.10.17.post0
Python Version: 3.6.8
Modul Version: 0.2.6

Modul: alteon_config_snmpv3_notify
Fatal: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 2 (char 79)

##### STEPS TO REPRODUCE
Info: All other snmpv3 modules work for me.
I used the following yaml code: 
```
---
- name: qick_test
  hosts: localhost
  tasks:
  - name: snmpv3_notify
    radware.radware_modules.alteon_config_snmpv3_notify:
      provider:
        server: 192.168.203.134
        user: user
        password: password
        validate_certs: no
        https_port: 443
        ssh_port: 22
        timeout: 5
      state: present
      revert_on_error: true
      parameters:
        name: Spectrum
        tag: Spectrum
...
```
Then i used the CLI: ansible-playbook qick_test.yaml --check
The error that occur is "json.decoder.JSONDecodeError"

##### EXPECTED RESULTS
I expected that the yaml file builds like snmpv3_general or the other snmp-modules do: For example:
```
---
- name: snmpv3
  hosts: localhost
  tasks:
   - name: snmpv3_general
     radware.radware_modules.alteon_config_snmp_general:
      provider:
        server: 192.168.203.134
        user: user
        password: password
        validate_certs: no
        https_port: 443
        ssh_port: 22
        timeout: 5
      state: present
      revert_on_error: true
      parameters:
         snmp_access: read_only
         sys_name: "..."
         sys_location: "..."
         sys_contact: "..."
         auth_ena_traps: enabled
...
```
```
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "parameters": {
                "auth_ena_traps": "enabled",
                "snmp_access": "read_only",
                "snmp_read_comm": null,
                "snmp_timeout": null,
                "snmp_trap1": null,
                "snmp_trap1_ipv6_addr": null,
                "snmp_trap2": null,
                "snmp_trap2_ipv6_addr": null,
                "snmp_v1v2_access": null,
                "snmp_write_comm": null,
                "sys_contact": "...",
                "sys_location": "...",
                "sys_name": "...",
                "trap_src_if": null
            },
            "provider": {
                "https_port": 443,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.203.134",
                "ssh_port": 22,
                "timeout": 5,
                "user": "user",
                "validate_certs": false
            },
            "revert_on_error": true,
            "state": "present",
            "write_on_change": false
        }
    },
    "obj": null,
    "status": "no change"
}
```

##### ACTUAL RESULTS
The Task [smnpv3_notify] fails. 

```
The full traceback is:
Traceback (most recent call last):
  File "/home/lukas/.ansible/tmp/ansible-tmp-1662112934.5732262-35137-57704506431678/AnsiballZ_alteon_config_snmpv3_notify.py", line 102, in <module>
    _ansiballz_main()
  File "/home/lukas/.ansible/tmp/ansible-tmp-1662112934.5732262-35137-57704506431678/AnsiballZ_alteon_config_snmpv3_notify.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/lukas/.ansible/tmp/ansible-tmp-1662112934.5732262-35137-57704506431678/AnsiballZ_alteon_config_snmpv3_notify.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.radware.radware_modules.plugins.modules.alteon_config_snmpv3_notify', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload_iyidjxau/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload.zip/ansible_collections/radware/radware_modules/plugins/modules/alteon_config_snmpv3_notify.py", line 171, in <module>
  File "/tmp/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload_iyidjxau/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload.zip/ansible_collections/radware/radware_modules/plugins/modules/alteon_config_snmpv3_notify.py", line 164, in main
  File "/tmp/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload_iyidjxau/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload.zip/ansible_collections/radware/radware_modules/plugins/module_utils/configuration.py", line 160, in exec_module
  File "/usr/local/lib/python3.6/site-packages/radware/sdk/configurator.py", line 496, in execute
    res, diff = self._execute_write_function(configurator, command, parameters, **kw)
  File "/usr/local/lib/python3.6/site-packages/radware/sdk/configurator.py", line 565, in _execute_write_function
    before_config = configurator.read(parameters)
  File "/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/alteon_configurator.py", line 50, in read
    return self._read(prepared_params)
  File "/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/configurators/snmpv3_notify.py", line 53, in _read
    self._read_device_beans(parameters)
  File "/usr/local/lib/python3.6/site-packages/radware/sdk/configurator.py", line 282, in _read_device_beans
    self._beans[bean_class] = self._device_api.read(bean_instance)
  File "/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py", line 111, in read
    all_result = self.read_all(bean, retries, timeout)
  File "/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py", line 124, in read_all
    response_data = self._read_all(bean, retries, timeout)
  File "/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py", line 247, in _read_all
    return self._alteon_response_processor(result, bean)
  File "/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py", line 260, in _alteon_response_processor
    json_out = rest_result.json()
  File "/usr/local/lib/python3.6/site-packages/radware/sdk/rest_driver.py", line 81, in json
    return _json.loads(self._content)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 2 (char 79)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/lukas/.ansible/tmp/ansible-tmp-1662112934.5732262-35137-57704506431678/AnsiballZ_alteon_config_snmpv3_notify.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/lukas/.ansible/tmp/ansible-tmp-1662112934.5732262-35137-57704506431678/AnsiballZ_alteon_config_snmpv3_notify.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/lukas/.ansible/tmp/ansible-tmp-1662112934.5732262-35137-57704506431678/AnsiballZ_alteon_config_snmpv3_notify.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.radware.radware_modules.plugins.modules.alteon_config_snmpv3_notify', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload_iyidjxau/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload.zip/ansible_collections/radware/radware_modules/plugins/modules/alteon_config_snmpv3_notify.py\", line 171, in <module>\n  File \"/tmp/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload_iyidjxau/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload.zip/ansible_collections/radware/radware_modules/plugins/modules/alteon_config_snmpv3_notify.py\", line 164, in main\n  File \"/tmp/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload_iyidjxau/ansible_radware.radware_modules.alteon_config_snmpv3_notify_payload.zip/ansible_collections/radware/radware_modules/plugins/module_utils/configuration.py\", line 160, in exec_module\n  File \"/usr/local/lib/python3.6/site-packages/radware/sdk/configurator.py\", line 496, in execute\n    res, diff = self._execute_write_function(configurator, command, parameters, **kw)\n  File \"/usr/local/lib/python3.6/site-packages/radware/sdk/configurator.py\", line 565, in _execute_write_function\n    before_config = configurator.read(parameters)\n  File \"/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/alteon_configurator.py\", line 50, in read\n    return self._read(prepared_params)\n  File \"/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/configurators/snmpv3_notify.py\", line 53, in _read\n    self._read_device_beans(parameters)\n  File \"/usr/local/lib/python3.6/site-packages/radware/sdk/configurator.py\", line 282, in _read_device_beans\n    self._beans[bean_class] = self._device_api.read(bean_instance)\n  File \"/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py\", line 111, in read\n    all_result = self.read_all(bean, retries, timeout)\n  File \"/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py\", line 124, in read_all\n    response_data = self._read_all(bean, retries, timeout)\n  File \"/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py\", line 247, in _read_all\n    return self._alteon_response_processor(result, bean)\n  File \"/usr/local/lib/python3.6/site-packages/radware/alteon/sdk/impl.py\", line 260, in _alteon_response_processor\n    json_out = rest_result.json()\n  File \"/usr/local/lib/python3.6/site-packages/radware/sdk/rest_driver.py\", line 81, in json\n    return _json.loads(self._content)\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 355, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 2 (char 79)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by EmmerichL** [comment]
The error has something to do with the version of the alteon device. The error occur at version 32.6.4.0, but not on 32.6.9.0. 32.6.4.0 seems unstable in general when it comes to ansible.
